# Generated by Django 5.0.6 on 2024-06-23 13:38

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_sharedwish_like_sharedwish_title'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SharedWish',
            new_name='MyWish',
        ),
    ]
