# Generated by Django 5.0.6 on 2024-06-24 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_sharedwish'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sharedwish',
            name='wish',
        ),
        migrations.DeleteModel(
            name='MyWish',
        ),
        migrations.DeleteModel(
            name='SharedWish',
        ),
    ]
