# Generated by Django 5.0.6 on 2024-06-24 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0006_sharedwish'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SharedWish',
        ),
    ]
