# Generated by Django 5.0.6 on 2024-06-24 22:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0008_mywish_sharedwish'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mywish',
            name='like',
        ),
        migrations.RemoveField(
            model_name='sharedwish',
            name='like',
        ),
        migrations.AddField(
            model_name='sharedwish',
            name='like',
            field=models.ManyToManyField(blank=True, related_name='sharedwish_likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
