# Generated by Django 5.0.6 on 2024-06-21 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='past',
            name='category',
        ),
        migrations.RemoveField(
            model_name='past',
            name='user',
        ),
        migrations.RemoveField(
            model_name='sharedwish',
            name='user',
        ),
        migrations.AlterField(
            model_name='talisman',
            name='talisman_category',
            field=models.CharField(max_length=10),
        ),
        migrations.DeleteModel(
            name='Future',
        ),
        migrations.DeleteModel(
            name='Past',
        ),
        migrations.DeleteModel(
            name='SharedWish',
        ),
    ]
